### ISSUE TITLE
agile-data in restart loop on resinOS

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-data#45]
After a fresh installation of stack v0.4.2 on resinOS 2.15.1, agile-data gets into a restart loop.

Log messages:
18.09.18 12:34:47 (+0200)  agile-data  hostname: you must be root to change the host name
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  mount: mount point /tmp/console is not a directory
18.09.18 12:34:47 (+0200)  agile-data  umount: /dev: must be superuser to unmount
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  mount: permission denied
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.885
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.886 warning: 32-bit servers don't have journaling enabled by default. Please use --journal if you want durability.
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.886
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.925 [initandlisten] MongoDB starting : pid=31 port=27017 dbpath=/data/db 32-bit host=agile-data
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.925 [initandlisten]
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.925 [initandlisten] ** NOTE: This is a 32 bit MongoDB binary.
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.925 [initandlisten] **       32 bit builds are limited to less than 2GB of data (or less with --journal).
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.926 [initandlisten] **       Note that journaling defaults to off for 32 bit and is currently off.
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.927 [initandlisten] **       See http://dochub.mongodb.org/core/32bit
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.927 [initandlisten]
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.927 [initandlisten] db version v2.4.10
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.927 [initandlisten] git version: nogitversion
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.927 [initandlisten] build info: Linux hartmann 3.16.0-4-armmp-lpae #1 SMP Debian 3.16.39-1 (2016-12-30) armv7l BOOST_LIB_VERSION=1_55
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.928 [initandlisten] allocator: system
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.928 [initandlisten] options: { dbpath: "/data/db", repair: true }
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.954 [initandlisten] ****
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.954 [initandlisten] ****
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.954 [initandlisten] need to upgrade database local with pdfile version 4.5, new version: 4.5
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.954 [initandlisten]    starting upgrade
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.954 [initandlisten]  local repairDatabase local
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.957 [FileAllocator] allocating new datafile /data/db/_tmp_repairDatabase_0/local.ns, filling with zeroes...
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.958 [FileAllocator] creating directory /data/db/_tmp_repairDatabase_0/_tmp
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.969 [FileAllocator] done allocating datafile /data/db/_tmp_repairDatabase_0/local.ns, size: 16MB,  took 0.004 secs
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.969 [FileAllocator] allocating new datafile /data/db/_tmp_repairDatabase_0/local.0, filling with zeroes...
18.09.18 12:34:47 (+0200)  agile-data  Tue Sep 18 10:34:47.975 [FileAllocator] done allocating datafile /data/db/_tmp_repairDatabase_0/local.0, size: 16MB,  took 0.005 secs
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.001 [initandlisten] finished checking dbs
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.001 dbexit:
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.001 [initandlisten] shutdown: going to close listening sockets...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.002 [initandlisten] shutdown: going to flush diaglog...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.002 [initandlisten] shutdown: going to close sockets...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.002 [initandlisten] shutdown: waiting for fs preallocator...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.002 [initandlisten] shutdown: closing all files...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.003 [initandlisten] closeAllFiles() finished
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.003 [initandlisten] shutdown: removing fs lock...
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.003 dbexit: really exiting now
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.112
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.113 warning: 32-bit servers don't have journaling enabled by default. Please use --journal if you want durability.
18.09.18 12:34:48 (+0200)  agile-data  Tue Sep 18 10:34:48.113
18.09.18 12:34:48 (+0200)  agile-data  about to fork child process, waiting until server is ready for connections.
18.09.18 12:34:48 (+0200)  agile-data  forked process: 39
18.09.18 12:34:48 (+0200)  agile-data  all output going to: /usr/src/app/mongod.log
18.09.18 12:34:48 (+0200)  agile-data  log file [/usr/src/app/mongod.log] exists; copied to temporary file [/usr/src/app/mongod.log.2018-09-18T10-34-48]
18.09.18 12:34:48 (+0200)  agile-data  child process started successfully, parent exiting
18.09.18 12:34:50 (+0200)  agile-data
18.09.18 12:34:50 (+0200)  agile-data  > agile-data@0.2.1 start /usr/src/app
18.09.18 12:34:50 (+0200)  agile-data  > node src/index.js
18.09.18 12:34:50 (+0200)  agile-data
18.09.18 12:34:52 (+0200)  agile-data  /usr/src/app/node_modules/mquery/lib/env.js:1
18.09.18 12:34:52 (+0200)  agile-data  (function (exports, require, module, __filename, __dirname) { `{k�jZa
18.09.18 12:34:52 (+0200)  agile-data                            ^
18.09.18 12:34:52 (+0200)  agile-data  SyntaxError: Invalid or unexpected token
18.09.18 12:34:52 (+0200)  agile-data      at createScript (vm.js:53:10)
18.09.18 12:34:52 (+0200)  agile-data      at Object.runInThisContext (vm.js:95:10)
18.09.18 12:34:52 (+0200)  agile-data      at Module._compile (module.js:543:28)
18.09.18 12:34:52 (+0200)  agile-data      at Object.Module._extensions..js (module.js:580:10)
18.09.18 12:34:52 (+0200)  agile-data      at Module.load (module.js:488:32)
18.09.18 12:34:52 (+0200)  agile-data      at tryModuleLoad (module.js:447:12)
18.09.18 12:34:52 (+0200)  agile-data      at Function.Module._load (module.js:439:3)
18.09.18 12:34:52 (+0200)  agile-data      at Module.require (module.js:498:17)
18.09.18 12:34:52 (+0200)  agile-data      at require (internal/module.js:20:19)
18.09.18 12:34:52 (+0200)  agile-data      at Object.<anonymous> (/usr/src/app/node_modules/mquery/lib/mquery.js:3034:13)
18.09.18 12:34:52 (+0200)  agile-data
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Linux 4.14.39
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! node v7.8.0
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! npm  v4.2.0
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! code ELIFECYCLE
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! errno 1
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! agile-data@0.2.1 start: `node src/index.js`
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Exit status 1
18.09.18 12:34:52 (+0200)  agile-data  npm ERR!
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Failed at the agile-data@0.2.1 start script 'node src/index.js'.
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Make sure you have the latest version of node.js and npm installed.
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! If you do, this is most likely a problem with the agile-data package,
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! not with npm itself.
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Tell the author that this fails on your system:
18.09.18 12:34:52 (+0200)  agile-data  npm ERR!     node src/index.js
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! You can get information on how to open an issue for this project with:
18.09.18 12:34:52 (+0200)  agile-data  npm ERR!     npm bugs agile-data
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Or if that isn't available, you can get their info via:
18.09.18 12:34:52 (+0200)  agile-data  npm ERR!     npm owner ls agile-data
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! There is likely additional logging output above.
18.09.18 12:34:52 (+0200)  agile-data
18.09.18 12:34:52 (+0200)  agile-data  npm ERR! Please include the following file with any support request:
18.09.18 12:34:52 (+0200)  agile-data  npm ERR!     /root/.npm/_logs/2018-09-18T10_34_52_866Z-debug.log
18.09.18 12:34:52 (+0200)  agile-data  /usr/bin/entry.sh: line 93: fg: job has terminated

**Comment by dpap** [comment]
I do remember that I had a similar issue before I enabled journalling on mongodb
 
I use this line in my docker-compose file
 command: "mongod --journal"
